sudo: false
language: ruby
rvm:
  - 2.3.3
before_install: gem install bundler -v 1.14.3

script: "bundle exec rake"

notifications:
  email:
    recipients:
      - john+fossicker@carney.id.au
    on_failure: change
    on_success: never
